C#_BookStore/Models/Purchase.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace C__BookStore.Models
{
    public class Purchase
    {
        public int purchase_id { get; set; }
        public string user_id { get; set; }
        public int product_id { get; set; }
        public string product_name { get; set; }
        public int quantity { get; set; }
        public float total_price { get; set; }
        public DateTime purchase_date { get; set; }
    }
}

C#_BookStore/Controllers/PurchaseController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using C__BookStore.Models;

namespace C__BookStore.Controllers
{
    public class PurchaseController : Controller
    {
        DbAccess db = new DbAccess();
        public ActionResult buyProducts(String uid, String pid, String p_name, String price, String quantity)
        {
            var model = new Purchase
            {
                user_id = uid, // however you get the user ID
                product_id = int.Parse(pid),
                product_name = p_name,
                total_price = float.Parse(price),
                quantity = Convert.ToInt32(quantity)
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Checkout(Purchase purchase)
        {
            String query = "select quantity from Products where product_id = " + purchase.product_id;

            db.OpenConnection();
            SqlDataReader sdr = db.GetData(query);
            int quantity = 0;
            if (sdr.Read())
            {
                quantity = int.Parse(sdr["quantity"].ToString());
                sdr.Close();
                db.CloseConnection();
            }

            if (quantity >= purchase.quantity)
            {
                purchase.total_price = purchase.total_price * purchase.quantity;
                var date = DateTime.Now;
                purchase.purchase_date = date.Date;

                query = $"insert into purchase values ('{purchase.user_id}', {purchase.product_id}, '{purchase.product_name}'," +
                    $"{purchase.quantity}, {purchase.total_price}, '{purchase.purchase_date}')";

                db.OpenConnection();
                db.InsertUpdateDelete(query);

                query = $"update Products set quantity = {quantity - purchase.quantity} where product_id = {purchase.product_id} ";
                db.InsertUpdateDelete(query);
                db.CloseConnection();

                ViewBag.purchase = "Purchase Sucessfull";
            }
            else
            {
                ViewBag.purchase = "Purchase Un-Sucessfull as quantity is high";
            }
            return RedirectToAction("showProducts", "Products");
        }
        
    }
}

C#_BookStore/Views/Purchase/buyProducts.cshtml
@model C__BookStore.Models.Purchase

@*@{
    Model.user_id = Request.QueryString["uid"];
    Model.product_id = int.Parse(Request.QueryString["pid"]);
    Model.product_name = Request.QueryString["p_name"];
    Model.total_price = float.Parse(Request.QueryString["price"]);
}*@


<div>
    <div style="border:2px solid black; border-radius: 5px; align-items:center">

        @using (Html.BeginForm("Checkout", "Purchase", FormMethod.Post))
        {
            <b>Product Name: </b> @Request.QueryString["p_name"]
            @Html.HiddenFor(model => model.product_name)

            <br />

            <b>Product Price: </b> @Request.QueryString["price"]
            @Html.HiddenFor(model => model.total_price)
            <br />

            @Html.HiddenFor(model => model.user_id)
            @Html.HiddenFor(model => model.product_id)

            <div class="form-group">
                @Html.LabelFor(model => model.quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.quantity, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Checkout" class="btn btn-default" />
                </div>
            </div>
        }

    </div>
</div>